### ISSUE TITLE
Permissions issue with Shot

### ISSUE THREAD

**Issue by DerekBeam** [davidvavra/showkase-screenshot-tests#10]
Is there any workaround for this? 

https://github.com/davidvavra/showkase-screenshot-tests/blob/shot/app/src/main/AndroidManifest.xml#L6

It's not ideal to add a permission to your app solely for snapshot tests.

**Comment by davidvavra** [comment]
You can add the permission only to the debug manifest, it doesn't have to be in main manifest. This way it won't be in the release app.

**Comment by DerekBeam** [comment]
Oh, interesting. I tried adding a manifest in only the `androidTest` folder with the permissions, but that didn't work. Honestly, I only assumed it would pick up that manifest but didn't consider debug. Let me try adding to a `debug` folder
