### ISSUE TITLE
Add Shot integration sample

### ISSUE THREAD

**Issue by RafaO** [davidvavra/showkase-screenshot-tests#2]
Hi! Thank you for this repo and the explicative blog post.

I was playing around with the code and I thought it might be interesting having a separate module to show how the integration with the library [Shot](https://github.com/pedrovgs/Shot).

I am happy to work on it and open a PR if it's something you would consider. It would require changing a bit the project's structure to allow different modules instead of only the app/feature one. Let me know if this is something you would consider including and I will proceed.

Thank you.

**Comment by davidvavra** [comment]
Hi, that's great! I can include it in a separate branch in this repo + I can link it to the original article.
